//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.23 at 10:11:38 AM BRT 
//

package br.org.funcate.glue.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * \brief This object contains factory methods for each Java content interface
 * and Java element interface generated in the generated package. An
 * ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 * @author
 * @version 1.0.0
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _AccessConstraints_QNAME = new QName("", "AccessConstraints");
	private final static QName _Format_QNAME = new QName("", "Format");
	private final static QName _Keyword_QNAME = new QName("", "Keyword");
	private final static QName _ContactPerson_QNAME = new QName("", "ContactPerson");
	private final static QName _ContactOrganization_QNAME = new QName("", "ContactOrganization");
	private final static QName _ContactElectronicMailAddress_QNAME = new QName("", "ContactElectronicMailAddress");
	private final static QName _Country_QNAME = new QName("", "Country");
	private final static QName _ContactPosition_QNAME = new QName("", "ContactPosition");
	private final static QName _Title_QNAME = new QName("", "Title");
	private final static QName _City_QNAME = new QName("", "City");
	private final static QName _Fees_QNAME = new QName("", "Fees");
	private final static QName _Name_QNAME = new QName("", "Name");
	private final static QName _PostCode_QNAME = new QName("", "PostCode");
	private final static QName _Address_QNAME = new QName("", "Address");
	private final static QName _AddressType_QNAME = new QName("", "AddressType");
	private final static QName _VendorSpecificCapabilities_QNAME = new QName("", "VendorSpecificCapabilities");
	private final static QName _SRS_QNAME = new QName("", "SRS");
	private final static QName _Abstract_QNAME = new QName("", "Abstract");
	private final static QName _StateOrProvince_QNAME = new QName("", "StateOrProvince");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link DescribeLayer }
	 * 
	 */
	public DescribeLayer createDescribeLayer() {
		return new DescribeLayer();
	}

	/**
	 * Create an instance of {@link ContactAddress }
	 * 
	 */
	public ContactAddress createContactAddress() {
		return new ContactAddress();
	}

	/**
	 * Create an instance of {@link KeywordList }
	 * 
	 */
	public KeywordList createKeywordList() {
		return new KeywordList();
	}

	/**
	 * Create an instance of {@link GetCapabilities }
	 * 
	 */
	public GetCapabilities createGetCapabilities() {
		return new GetCapabilities();
	}

	/**
	 * Create an instance of {@link ContactInformation }
	 * 
	 */
	public ContactInformation createContactInformation() {
		return new ContactInformation();
	}

	/**
	 * Create an instance of {@link Service }
	 * 
	 */
	public Service createService() {
		return new Service();
	}

	/**
	 * Create an instance of {@link OnlineResource }
	 * 
	 */
	public OnlineResource createOnlineResource() {
		return new OnlineResource();
	}

	/**
	 * Create an instance of {@link GetStyles }
	 * 
	 */
	public GetStyles createGetStyles() {
		return new GetStyles();
	}

	/**
	 * Create an instance of {@link Request }
	 * 
	 */
	public Request createRequest() {
		return new Request();
	}

	/**
	 * Create an instance of {@link ContactPersonPrimary }
	 * 
	 */
	public ContactPersonPrimary createContactPersonPrimary() {
		return new ContactPersonPrimary();
	}

	/**
	 * Create an instance of {@link HTTP }
	 * 
	 */
	public HTTP createHTTP() {
		return new HTTP();
	}

	/**
	 * Create an instance of {@link GetMap }
	 * 
	 */
	public GetMap createGetMap() {
		return new GetMap();
	}

	/**
	 * Create an instance of {@link Capability }
	 * 
	 */
	public Capability createCapability() {
		return new Capability();
	}

	/**
	 * Create an instance of {@link Post }
	 * 
	 */
	public Post createPost() {
		return new Post();
	}

	/**
	 * Create an instance of {@link LatLonBoundingBox }
	 * 
	 */
	public LatLonBoundingBox createLatLonBoundingBox() {
		return new LatLonBoundingBox();
	}

	/**
	 * Create an instance of {@link Exception }
	 * 
	 */
	public Exception createException() {
		return new Exception();
	}

	/**
	 * Create an instance of {@link WMTMSCapabilities }
	 * 
	 */
	public WMTMSCapabilities createWMTMSCapabilities() {
		return new WMTMSCapabilities();
	}

	/**
	 * Create an instance of {@link UserDefinedSymbolization }
	 * 
	 */
	public UserDefinedSymbolization createUserDefinedSymbolization() {
		return new UserDefinedSymbolization();
	}

	/**
	 * Create an instance of {@link BoundingBox }
	 * 
	 */
	public BoundingBox createBoundingBox() {
		return new BoundingBox();
	}

	/**
	 * Create an instance of {@link DCPType }
	 * 
	 */
	public DCPType createDCPType() {
		return new DCPType();
	}

	/**
	 * Create an instance of {@link LegendURL }
	 * 
	 */
	public LegendURL createLegendURL() {
		return new LegendURL();
	}

	/**
	 * Create an instance of {@link Layer }
	 * 
	 */
	public Layer createLayer() {
		return new Layer();
	}

	/**
	 * Create an instance of {@link Style }
	 * 
	 */
	public Style createStyle() {
		return new Style();
	}

	/**
	 * Create an instance of {@link GetLegendGraphic }
	 * 
	 */
	public GetLegendGraphic createGetLegendGraphic() {
		return new GetLegendGraphic();
	}

	/**
	 * Create an instance of {@link Get }
	 * 
	 */
	public Get createGet() {
		return new Get();
	}

	/**
	 * Create an instance of {@link GetFeatureInfo }
	 * 
	 */
	public GetFeatureInfo createGetFeatureInfo() {
		return new GetFeatureInfo();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "AccessConstraints")
	public JAXBElement<String> createAccessConstraints(String value) {
		return new JAXBElement<String>(_AccessConstraints_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Format")
	public JAXBElement<String> createFormat(String value) {
		return new JAXBElement<String>(_Format_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Keyword")
	public JAXBElement<String> createKeyword(String value) {
		return new JAXBElement<String>(_Keyword_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ContactPerson")
	public JAXBElement<String> createContactPerson(String value) {
		return new JAXBElement<String>(_ContactPerson_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ContactOrganization")
	public JAXBElement<String> createContactOrganization(String value) {
		return new JAXBElement<String>(_ContactOrganization_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ContactElectronicMailAddress")
	public JAXBElement<String> createContactElectronicMailAddress(String value) {
		return new JAXBElement<String>(_ContactElectronicMailAddress_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Country")
	public JAXBElement<String> createCountry(String value) {
		return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ContactPosition")
	public JAXBElement<String> createContactPosition(String value) {
		return new JAXBElement<String>(_ContactPosition_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Title")
	public JAXBElement<String> createTitle(String value) {
		return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "City")
	public JAXBElement<String> createCity(String value) {
		return new JAXBElement<String>(_City_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Fees")
	public JAXBElement<String> createFees(String value) {
		return new JAXBElement<String>(_Fees_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Name")
	public JAXBElement<String> createName(String value) {
		return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PostCode")
	public JAXBElement<String> createPostCode(String value) {
		return new JAXBElement<String>(_PostCode_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Address")
	public JAXBElement<String> createAddress(String value) {
		return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "AddressType")
	public JAXBElement<String> createAddressType(String value) {
		return new JAXBElement<String>(_AddressType_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VendorSpecificCapabilities")
	public JAXBElement<String> createVendorSpecificCapabilities(String value) {
		return new JAXBElement<String>(_VendorSpecificCapabilities_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SRS")
	public JAXBElement<String> createSRS(String value) {
		return new JAXBElement<String>(_SRS_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Abstract")
	public JAXBElement<String> createAbstract(String value) {
		return new JAXBElement<String>(_Abstract_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "StateOrProvince")
	public JAXBElement<String> createStateOrProvince(String value) {
		return new JAXBElement<String>(_StateOrProvince_QNAME, String.class, null, value);
	}

}
